inserir caixa de observações
wizards-of-api/avaliacao-360 pull request #27
Opened 2023-04-26 15:03 UTC by danielvdbarbosa

Realizada a inserção de uma caixa que capturará um comentário sobre a avaliação de um aluno realizada. Realizei também a quebra de uma linha entre cada pergunta, a fim de melhorar a experiencia do usuário.

2023-04-28 18:57 UTC, MarcyLeite requested changes
Além dessas mudanças, seria bom botar o texto da pergunta como texto no lugar de titulo não? É possivel que tenha algumas perguntas muito grandes que cortam pelo tamanho da janela.

2023-04-28 18:57 UTC, MarcyLeite commented on avaliacao360/interface/evaluation.py
> +                    result.append({'value':1, 'feedback':feedback})
```suggestion
                    feedback = None
                    while not feedback or feedback == "":
                        feedback = sg.popup_get_text(
                            "Justifique sua resposta: ",
                            title=question_list[int(group_id[-1])]
                            )
                    result.append({'value':1, 'feedback':feedback})

```
Recomendo fazer uma mudança assim. Isso impediria que usuario passe sem responder, seja só clicando no continuar ou fechando a janela

2023-04-28 18:57 UTC, MarcyLeite commented on avaliacao360/interface/evaluation.py
> +                    result.append({'value':2, 'feedback':feedback})
```suggestion
                    feedback = sg.popup_get_text(
                        "Justifique sua resposta: ",
                        title=question_list[int(group_id[-1])]
                        )
                    result.append({'value':2, 'feedback':feedback})
```
Mesma coisa que o do `if values['1_' + group_id]`

2023-04-28 19:10 UTC, danielvdbarbosa commented on avaliacao360/interface/evaluation.py
> +                    result.append({'value':1, 'feedback':feedback})
Correção realizada.

2023-05-02 17:09 UTC, MarcyLeite commented on avaliacao360/interface/evaluation.py
> +                    result.append({'value':2, 'feedback':feedback})
Resolvido no [1ffdf70](https://github.com/wizards-of-api/avaliacao-360/pull/27/commits/1ffdf709dc1fb13ef65a3d43204afff5b72dc813) e [38fbca8](https://github.com/wizards-of-api/avaliacao-360/pull/27/commits/38fbca875c7717c1b827a1bfead26927c08c07a3)

2023-05-02 17:10 UTC, MarcyLeite commented on avaliacao360/interface/evaluation.py
> +                    result.append({'value':1, 'feedback':feedback})
resolvido [1ffdf70](https://github.com/wizards-of-api/avaliacao-360/pull/27/commits/1ffdf709dc1fb13ef65a3d43204afff5b72dc813) e [38fbca8](https://github.com/wizards-of-api/avaliacao-360/pull/27/commits/38fbca875c7717c1b827a1bfead26927c08c07a3)

2023-05-02 17:10 UTC, MarcyLeite approved these changes

2023-05-02 17:11 UTC, merged